'use client';

import { useEffect, useState } from 'react';
import { CalendarClock, CreditCard, Landmark, Plus } from 'lucide-react';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { SUPPORTED_CURRENCIES } from '@/lib/finance/contracts/enums';
import { currencyInputMode, currencyInputPlaceholder, formatMoneyMinor, majorToMinorExact } from '@/lib/finance/money/presentation';

function ReviewBadge({ value }) {
  return <Badge variant={value === 'confirmed' ? 'default' : 'outline'}>{value === 'confirmed' ? '已確認' : '待確認'}</Badge>;
}

function CreateDialog({ kind, open, accounts, onOpenChange, onSaved }) {
  const [form, setForm] = useState({}); const [saving, setSaving] = useState(false); const [error, setError] = useState(null);
  useEffect(() => { if (open) { setForm({ currency: 'TWD', cadence: 'monthly', rate_type: 'unknown', payment_frequency: 'monthly', direction: 'out' }); setError(null); } }, [open, kind]);
  const eligible = accounts.filter((account) => kind === 'card' ? account.account_kind === 'credit_card' : account.account_kind === 'loan' || account.account_kind === 'payable');
  const selectedAccount = eligible.find((account) => account.account_key === form.account_key);
  const activeCurrency = kind === 'commitment' ? form.currency : selectedAccount?.currency || form.currency || 'TWD';
  function field(name, value) { setForm((current) => ({ ...current, [name]: value })); }
  function selectAccount(value) {
    const account = eligible.find((item) => item.account_key === value);
    setForm((current) => ({ ...current, account_key: value, currency: account?.currency || current.currency || 'TWD' }));
  }
  async function submit(event) {
    event.preventDefault(); setSaving(true); setError(null);
    try {
      let url; let payload;
      if (kind === 'card') {
        url = '/api/finance/credit-cards';
        payload = { account_key: form.account_key, statement_close_day: form.statement_close_day ? Number(form.statement_close_day) : null, payment_due_day: form.payment_due_day ? Number(form.payment_due_day) : null, credit_limit_minor: form.amount ? majorToMinorExact(form.amount, activeCurrency) : null, currency: activeCurrency, authority: 'user_confirmed', review_state: 'confirmed' };
      } else if (kind === 'liability') {
        url = '/api/finance/liabilities';
        payload = { account_key: form.account_key, liability_kind: form.liability_kind, original_principal_minor: majorToMinorExact(form.amount, activeCurrency), currency: activeCurrency, rate_type: form.rate_type, apr_decimal: form.apr_decimal || null, start_date: form.start_date, maturity_date: form.maturity_date || null, payment_frequency: form.payment_frequency, authority: 'user_confirmed', review_state: 'confirmed' };
      } else {
        url = '/api/finance/commitments';
        payload = { entity_key: 'personal', commitment_kind: form.commitment_kind, direction: form.direction, amount_kind: 'fixed', amount_minor: majorToMinorExact(form.amount, activeCurrency), currency: activeCurrency, cadence: form.cadence, start_date: form.start_date, next_due_date: form.next_due_date || null, status: 'scheduled', authority: 'user_confirmed', review_state: 'confirmed' };
      }
      const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) });
      const body = await response.json();
      if (!response.ok) throw new Error(body?.error?.message || '資料儲存失敗');
      onOpenChange(false); await onSaved();
    } catch (reason) { setError(reason.message); } finally { setSaving(false); }
  }
  const title = kind === 'card' ? '建立信用卡資料' : kind === 'liability' ? '建立負債資料' : '新增固定收支';
  return <Dialog open={open} onOpenChange={(next) => !saving && onOpenChange(next)}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>由你輸入的資料會標記為已確認；官方帳單與還款表仍應保留來源證據。</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4" aria-describedby={error ? 'obligation-form-error' : undefined}>
    {kind !== 'commitment' ? <div className="space-y-2"><Label htmlFor="obligation-account">帳戶</Label><Select value={form.account_key || ''} onValueChange={selectAccount} required><SelectTrigger id="obligation-account" className="min-h-12 w-full"><SelectValue placeholder="選擇已建立的帳戶" /></SelectTrigger><SelectContent>{eligible.map((account) => <SelectItem key={account.account_key} value={account.account_key}>{account.display_name} · {account.currency}</SelectItem>)}</SelectContent></Select>{eligible.length === 0 ? <p className="text-xs text-muted-foreground">請先在帳戶分頁建立對應類型的帳戶。</p> : null}</div> : null}
    {kind === 'card' ? <><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="close-day">結帳日</Label><Input id="close-day" name="statement_close_day" inputMode="numeric" min="1" max="31" value={form.statement_close_day || ''} onChange={(event) => field('statement_close_day', event.target.value)} /></div><div className="space-y-2"><Label htmlFor="due-day">繳款日</Label><Input id="due-day" name="payment_due_day" inputMode="numeric" min="1" max="31" value={form.payment_due_day || ''} onChange={(event) => field('payment_due_day', event.target.value)} /></div></div><div className="space-y-2"><Label htmlFor="credit-limit">信用額度（{activeCurrency}）</Label><Input id="credit-limit" name="credit_limit" inputMode={currencyInputMode(activeCurrency)} placeholder={currencyInputPlaceholder(activeCurrency)} value={form.amount || ''} onChange={(event) => field('amount', event.target.value)} /></div></> : null}
    {kind === 'liability' ? <><div className="space-y-2"><Label htmlFor="liability-kind">負債種類</Label><Input id="liability-kind" name="liability_kind" value={form.liability_kind || ''} onChange={(event) => field('liability_kind', event.target.value)} placeholder="例如：信貸、房貸" required /></div><div className="space-y-2"><Label htmlFor="principal">原始本金（{activeCurrency}）</Label><Input id="principal" name="original_principal" inputMode={currencyInputMode(activeCurrency)} placeholder={currencyInputPlaceholder(activeCurrency)} value={form.amount || ''} onChange={(event) => field('amount', event.target.value)} required /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="loan-start">起始日</Label><Input id="loan-start" name="start_date" type="date" value={form.start_date || ''} onChange={(event) => field('start_date', event.target.value)} required /></div><div className="space-y-2"><Label htmlFor="loan-end">到期日</Label><Input id="loan-end" name="maturity_date" type="date" value={form.maturity_date || ''} onChange={(event) => field('maturity_date', event.target.value)} /></div></div><div className="space-y-2"><Label htmlFor="apr">已知年利率（小數，可留白）</Label><Input id="apr" name="apr_decimal" inputMode="decimal" value={form.apr_decimal || ''} onChange={(event) => field('apr_decimal', event.target.value)} placeholder="例如 0.021" /></div></> : null}
    {kind === 'commitment' ? <><div className="space-y-2"><Label htmlFor="commitment-kind">項目</Label><Input id="commitment-kind" name="commitment_kind" value={form.commitment_kind || ''} onChange={(event) => field('commitment_kind', event.target.value)} placeholder="例如：房租、薪資、保險" required /></div><div className="grid gap-4 sm:grid-cols-3"><div className="space-y-2"><Label htmlFor="commitment-direction">方向</Label><Select value={form.direction} onValueChange={(value) => field('direction', value)}><SelectTrigger id="commitment-direction" className="min-h-12 w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="out">支出</SelectItem><SelectItem value="in">收入</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label htmlFor="commitment-currency">幣別</Label><Select value={form.currency} onValueChange={(value) => field('currency', value)}><SelectTrigger id="commitment-currency" className="min-h-12 w-full"><SelectValue /></SelectTrigger><SelectContent>{SUPPORTED_CURRENCIES.map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="commitment-amount">金額（{activeCurrency}）</Label><Input id="commitment-amount" name="amount" inputMode={currencyInputMode(activeCurrency)} placeholder={currencyInputPlaceholder(activeCurrency)} value={form.amount || ''} onChange={(event) => field('amount', event.target.value)} required /></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="commitment-start">起始日</Label><Input id="commitment-start" name="start_date" type="date" value={form.start_date || ''} onChange={(event) => field('start_date', event.target.value)} required /></div><div className="space-y-2"><Label htmlFor="commitment-next">下次日期</Label><Input id="commitment-next" name="next_due_date" type="date" value={form.next_due_date || ''} onChange={(event) => field('next_due_date', event.target.value)} /></div></div></> : null}
    {error ? <p id="obligation-form-error" className="text-sm text-destructive" role="alert">{error}</p> : null}<DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>取消</Button><Button type="submit" disabled={saving || (kind !== 'commitment' && !form.account_key)}>{saving ? '儲存中' : '儲存'}</Button></DialogFooter>
  </form></DialogContent></Dialog>;
}

function Empty({ children }) { return <div className="rounded-md border border-dashed px-5 py-8 text-center text-sm text-muted-foreground">{children}</div>; }

export default function ObligationRegister({ inventory, onSaved }) {
  const [dialog, setDialog] = useState(null);
  const cards = inventory.credit_cards || []; const liabilities = inventory.liabilities || []; const commitments = inventory.commitments || [];
  const debt = inventory.readiness?.debt_obligations;
  return <div className="space-y-8">
    <section className="grid gap-4 border-b pb-6 md:grid-cols-[minmax(0,1.4fr)_minmax(14rem,0.8fr)]"><div><div className="flex flex-wrap items-center gap-2"><Landmark className="size-5 text-primary" aria-hidden="true" /><h2 className="font-semibold">負債資料準備度</h2><Badge variant={debt?.status === 'complete' ? 'default' : 'outline'}>{debt?.status === 'complete' ? '可分析' : '資料不完整'}</Badge></div><p className="mt-2 text-sm text-muted-foreground">信用卡帳單、未出帳與貸款本金分開保存，避免付款被重複算成消費。</p></div><div className="text-sm"><p className="font-medium">仍需處理 {debt?.gaps?.length || 0} 個缺口</p><p className="mt-1 text-muted-foreground">{debt?.gaps?.[0]?.next_action || debt?.gaps?.[0]?.gap || '目前沒有阻擋分析的缺口。'}</p></div></section>
    <section className="space-y-3"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><CreditCard className="size-5 text-primary" aria-hidden="true" /><h2 className="font-semibold">信用卡</h2><span className="text-sm tabular-nums text-muted-foreground">{cards.length}</span></div><Button size="sm" variant="outline" onClick={() => setDialog('card')}><Plus aria-hidden="true" />建立資料</Button></div>{cards.length ? <div className="divide-y rounded-md border">{cards.map((card) => <article key={card.profile_key} className="grid gap-3 px-4 py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium">{card.display_name}</h3><ReviewBadge value={card.review_state} /></div><p className="mt-1 text-xs text-muted-foreground">結帳日 {card.statement_close_day || '未提供'} · 繳款日 {card.payment_due_day || '未提供'} · {card.statements.length} 期帳單 · {card.installments.length} 筆分期計畫</p></div><p className="font-mono text-sm tabular-nums">額度 {formatMoneyMinor(card.credit_limit_minor, card.currency, { emptyLabel: '金額未定' })}</p></article>)}</div> : <Empty>尚未建立信用卡 profile。先建立信用卡帳戶，再補上結帳與繳款條件。</Empty>}</section>
    <section className="space-y-3"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Landmark className="size-5 text-primary" aria-hidden="true" /><h2 className="font-semibold">貸款與應付款</h2><span className="text-sm tabular-nums text-muted-foreground">{liabilities.length}</span></div><Button size="sm" variant="outline" onClick={() => setDialog('liability')}><Plus aria-hidden="true" />建立資料</Button></div>{liabilities.length ? <div className="divide-y rounded-md border">{liabilities.map((item) => <article key={item.liability_key} className="grid gap-3 px-4 py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium">{item.display_name}</h3><ReviewBadge value={item.review_state} /></div><p className="mt-1 text-xs text-muted-foreground">{item.liability_kind} · {item.payment_frequency} · {item.schedule.length} 期官方還款資料</p></div><p className="font-mono text-sm tabular-nums">原始本金 {formatMoneyMinor(item.original_principal_minor, item.currency, { emptyLabel: '金額未定' })}</p></article>)}</div> : <Empty>尚未建立貸款或應付款資料。AI 不會只憑 APR 猜還款表。</Empty>}</section>
    <section className="space-y-3"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><CalendarClock className="size-5 text-primary" aria-hidden="true" /><h2 className="font-semibold">固定收支</h2><span className="text-sm tabular-nums text-muted-foreground">{commitments.length}</span></div><Button size="sm" variant="outline" onClick={() => setDialog('commitment')}><Plus aria-hidden="true" />新增項目</Button></div>{commitments.length ? <div className="divide-y rounded-md border">{commitments.map((item) => <article key={item.commitment_key} className="grid gap-3 px-4 py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium">{item.commitment_kind}</h3><ReviewBadge value={item.review_state} /></div><p className="mt-1 text-xs text-muted-foreground">{item.direction === 'in' ? '收入' : '支出'} · {item.cadence} · 下次 {item.next_due_date || '未指定'}</p></div><p className="font-mono text-sm tabular-nums">{formatMoneyMinor(item.amount_minor, item.currency, { emptyLabel: '金額未定' })}</p></article>)}</div> : <Empty>尚未建立固定收入或支出。這些資料會成為後續現金流預測的前置條件。</Empty>}</section>
    <CreateDialog kind={dialog} open={Boolean(dialog)} accounts={inventory.accounts || []} onOpenChange={(open) => !open && setDialog(null)} onSaved={onSaved} />
  </div>;
}
