'use client';

import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, ArrowRightLeft, GitMerge, ListChecks, RefreshCw } from 'lucide-react';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { displayPositionType, displayResourceType, displayTaskKind, displayValuationMethod } from '@/lib/finance/presentation-labels';
import { formatCurrencyMinor } from '@/lib/format';

function money(value, currency = 'TWD') { return formatCurrencyMinor(value, currency, { missing: '尚無估值' }); }

function ConflictDialog({ conflict, open, onOpenChange, onSaved }) {
  const [selected, setSelected] = useState(''); const [note, setNote] = useState(''); const [error, setError] = useState(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setSelected(''); setNote(''); setError(null); } }, [open, conflict]);
  async function submit(event) { event.preventDefault(); setSaving(true); setError(null); try { const response = await fetch(`/api/finance/source-conflicts/${conflict.conflict_key}/resolve`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ selected_source_key: selected, resolution_note: note }) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || '衝突處理失敗'); onOpenChange(false); await onSaved(); } catch (reason) { setError(reason.message); } finally { setSaving(false); } }
  return <Dialog open={open} onOpenChange={(next) => !saving && onOpenChange(next)}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>裁決來源衝突</DialogTitle><DialogDescription>{conflict?.target_context} · {conflict?.semantic_key}</DialogDescription></DialogHeader>{conflict ? <form className="space-y-4" onSubmit={submit}><div className="space-y-2"><Label htmlFor="conflict-source">採用來源</Label><Select value={selected} onValueChange={setSelected}><SelectTrigger id="conflict-source" className="w-full"><SelectValue placeholder="選擇保留的證據" /></SelectTrigger><SelectContent><SelectItem value={conflict.left_source_key}>{conflict.left_source_key}</SelectItem><SelectItem value={conflict.right_source_key}>{conflict.right_source_key}</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label htmlFor="conflict-note">判斷依據</Label><Input id="conflict-note" value={note} onChange={(event) => setNote(event.target.value)} required maxLength={1000} /></div>{error ? <p className="text-sm text-destructive" role="alert">{error}</p> : null}<DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>取消</Button><Button type="submit" disabled={saving || !selected || !note.trim()}>{saving ? '儲存中' : '確認裁決'}</Button></DialogFooter></form> : null}</DialogContent></Dialog>;
}

export default function ReconciliationRegister({ inventory, onSaved }) {
  const [conflicts, setConflicts] = useState([]); const [selectedConflict, setSelectedConflict] = useState(null); const [merge, setMerge] = useState({ type: 'account', source: '', target: '', preview: null, error: null, loading: false, proposed: false });
  const loadConflicts = useCallback(async () => { const response = await fetch('/api/finance/source-conflicts?status=open', { cache: 'no-store' }); const body = await response.json(); if (response.ok) setConflicts(body.conflicts || []); }, []);
  useEffect(() => { loadConflicts(); }, [loadConflicts]);
  const reconciliation = inventory.reconciliation; const tasks = inventory.review_tasks || []; const items = inventory.valued_items || [];
  async function previewMerge(event) { event.preventDefault(); setMerge((current) => ({ ...current, loading: true, error: null, preview: null, proposed: false })); try { const response = await fetch('/api/finance/identity-merges/preview', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ resource_type: merge.type, source_key: merge.source, target_key: merge.target }) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || '合併預覽失敗'); setMerge((current) => ({ ...current, loading: false, preview: body.preview })); } catch (reason) { setMerge((current) => ({ ...current, loading: false, error: reason.message })); } }
  async function proposeMerge() { const action = `merge_${merge.preview.resource_type}`; const response = await fetch('/api/finance/human-confirmations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action_kind: action, resource_type: 'identity_merge', resource_key: merge.preview.source_key, payload: merge.preview, expected_version: merge.preview.source_version }) }); const body = await response.json(); if (!response.ok) { setMerge((current) => ({ ...current, error: body?.error?.message || '確認提案建立失敗' })); return; } setMerge((current) => ({ ...current, proposed: true })); }
  async function savedConflict() { await Promise.all([loadConflicts(), onSaved()]); }
  return <div className="space-y-8">
    <section className="grid gap-4 border-b pb-6 md:grid-cols-[minmax(0,1.4fr)_minmax(14rem,0.8fr)]"><div><div className="flex flex-wrap items-center gap-2"><ArrowRightLeft className="size-5 text-primary" aria-hidden="true" /><h2 className="font-semibold">跨資料對帳</h2><Badge variant={reconciliation.status === 'complete' ? 'default' : 'outline'}>{reconciliation.status === 'complete' ? '已對上' : '尚未對齊'}</Badge></div><p className="mt-2 text-sm text-muted-foreground">轉帳、卡款、貸款與投資現金腳分開配對，避免同一筆資金重複計算。</p></div><dl className="grid grid-cols-2 gap-3 text-sm"><div><dt className="text-muted-foreground">單邊轉帳</dt><dd className="mt-1 font-mono text-lg">{reconciliation.one_sided_transfers.length}</dd></div><div><dt className="text-muted-foreground">跨資料範圍衝突</dt><dd className="mt-1 font-mono text-lg">{reconciliation.duplicate_context_conflicts.length}</dd></div></dl></section>
    <section className="space-y-3"><div className="flex items-center gap-2"><ListChecks className="size-5 text-primary" aria-hidden="true" /><h2 className="font-semibold">待審工作</h2><span className="text-sm tabular-nums text-muted-foreground">{tasks.length}</span><Button variant="ghost" size="icon-sm" className="ml-auto" aria-label="重新整理待審工作" onClick={onSaved}><RefreshCw aria-hidden="true" /></Button></div>{tasks.length ? <div className="divide-y rounded-md border">{tasks.map((task) => <article key={task.task_key} className="flex flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{displayTaskKind(task.task_kind)}</Badge><p className="truncate font-medium">{task.reason}</p></div><p className="mt-1 truncate text-xs text-muted-foreground">{displayResourceType(task.resource_type)}</p><details className="mt-1 text-[11px] text-muted-foreground"><summary className="w-fit cursor-pointer">查看系統識別碼</summary><p className="mt-1 break-all font-mono">{task.resource_key}</p></details></div>{task.conflict_key ? <Button size="sm" onClick={() => setSelectedConflict(conflicts.find((item) => item.conflict_key === task.conflict_key) || null)}><AlertTriangle aria-hidden="true" />處理衝突</Button> : <Badge variant="secondary">等待來源或人工判斷</Badge>}</article>)}</div> : <div className="rounded-md border border-dashed px-5 py-8 text-center text-sm text-muted-foreground">目前沒有待審工作。</div>}</section>
    <section className="space-y-3"><div className="flex items-center gap-2"><ListChecks className="size-5 text-primary" aria-hidden="true" /><h2 className="font-semibold">人工估值</h2><span className="text-sm tabular-nums text-muted-foreground">{items.length}</span></div>{items.length ? <div className="divide-y rounded-md border">{items.map((item) => <article key={item.item_key} className="grid gap-2 px-4 py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><p className="font-medium">{item.display_name}</p><p className="text-xs text-muted-foreground">{displayPositionType(item.item_type)} · {displayValuationMethod(item.latest_valuation?.valuation_method)} · {item.latest_valuation?.as_of_date || '未提供日期'}</p></div><p className="font-mono font-semibold sm:text-right">{money(item.latest_valuation?.value_minor,item.latest_valuation?.currency)}</p></article>)}</div> : <p className="rounded-md border border-dashed px-5 py-8 text-center text-sm text-muted-foreground">尚無房產、車輛或私人應收等人工估值。</p>}</section>
    <section className="space-y-4 border-t pt-6"><div className="flex items-center gap-2"><GitMerge className="size-5 text-primary" aria-hidden="true" /><h2 className="font-semibold">重複身分合併預覽</h2></div><form className="grid gap-3 md:grid-cols-[10rem_minmax(0,1fr)_minmax(0,1fr)_auto] md:items-end" onSubmit={previewMerge}><div className="space-y-2"><Label htmlFor="merge-type">類型</Label><Select value={merge.type} onValueChange={(type) => setMerge((current) => ({ ...current, type, preview: null }))}><SelectTrigger id="merge-type"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="institution">機構</SelectItem><SelectItem value="account">帳戶</SelectItem><SelectItem value="instrument">投資標的</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label htmlFor="merge-source">舊識別碼</Label><Input id="merge-source" value={merge.source} onChange={(event) => setMerge((current) => ({ ...current, source: event.target.value }))} required /></div><div className="space-y-2"><Label htmlFor="merge-target">保留識別碼</Label><Input id="merge-target" value={merge.target} onChange={(event) => setMerge((current) => ({ ...current, target: event.target.value }))} required /></div><Button type="submit" variant="outline" disabled={merge.loading}>{merge.loading ? '檢查中' : '預覽影響'}</Button></form>{merge.error ? <Alert variant="destructive"><AlertDescription>{merge.error}</AlertDescription></Alert> : null}{merge.preview ? <div className="flex flex-col gap-3 rounded-md border px-4 py-4 sm:flex-row sm:items-center"><div className="flex-1"><p className="font-medium">影響 {merge.preview.impacts.reduce((sum,item)=>sum+item.rows,0)} 筆資料；碰撞 {merge.preview.collisions.length} 項</p><p className="mt-1 text-xs text-muted-foreground">影響摘要識別碼：{merge.preview.impact_hash}</p></div><Button disabled={!merge.preview.can_merge || merge.proposed} onClick={proposeMerge}>{merge.proposed ? '已送交確認' : '送交人工確認'}</Button></div> : null}</section>
    <ConflictDialog conflict={selectedConflict} open={Boolean(selectedConflict)} onOpenChange={(open) => !open && setSelectedConflict(null)} onSaved={savedConflict} />
  </div>;
}
